lista = [
    { 'ticker': 'AAPL',	'ratio': 10,	'nombre': 'Apple Inc.'},
    { 'ticker': 'ABEV',	'ratio': 0.33,	'nombre': 'Ambev SA - ADR'},
    { 'ticker': 'ABT',	'ratio': 2,	'nombre': 'Abbott Laboratories'},
    { 'ticker': 'ADBE',	'ratio': 11,	'nombre': 'Adobe Inc'},
    { 'ticker': 'AGRO',	'ratio': 40,	'nombre': 'Adecoagro SA'},
    { 'ticker': 'AIG',	'ratio': 5,	'nombre': 'American International Group Inc'},
    { 'ticker': 'AMD',	'ratio': 0.5,	'nombre': 'Advanced Micro Devices, Inc.'},
    { 'ticker': 'AMGN',	'ratio': 5,	'nombre': 'Amgen, Inc.'},
    { 'ticker': 'AMX',	'ratio': 1,	'nombre': 'America Movil SAB de CV ADR Series L'},
    { 'ticker': 'AMZN',	'ratio': 72,	'nombre': 'Amazon.com, Inc.'},
    { 'ticker': 'ARCO',	'ratio': 0.5,	'nombre': 'Arcos Dorados Holdings Inc'},
    { 'ticker': 'AUY',	'ratio': 1,	'nombre': 'Yamana Gold Inc'},
    { 'ticker': 'AXP',	'ratio': 5,	'nombre': 'American Express Company'},
    { 'ticker': 'BA',	'ratio': 3,	'nombre': 'Boeing Co'},
    { 'ticker': 'BABA',	'ratio': 9,	'nombre': 'Alibaba Group Holding Ltd - ADR'},
    { 'ticker': 'BBD',	'ratio': 1,	'nombre': 'Banco Bradesco SA'},
    { 'ticker': 'BCS',	'ratio': 1,	'nombre': 'Barclays PLC'},
    { 'ticker': 'BHP',	'ratio': 1,	'nombre': 'BHP Group Ltd'},
    { 'ticker': 'BIDU',	'ratio': 11,	'nombre': 'Baidu Inc'},
    { 'ticker': 'BIIB',	'ratio': 13,	'nombre': 'Biogen Inc'},
    { 'ticker': 'BMY',	'ratio': 1,	'nombre': 'Bristol-Myers Squibb Co'},
    { 'ticker': 'BP',	'ratio': 5,	'nombre': 'BP plc'},
    { 'ticker': 'BRFS',	'ratio': 0.33,	'nombre': 'BRF S.A. (ADR) common stock'},
    { 'ticker': 'BSBR',	'ratio': 1,	'nombre': 'Banco Santander Brasil SA ADR'},
    { 'ticker': 'C',	'ratio': 3,	'nombre': 'Citigroup Inc'},
    { 'ticker': 'CAT',	'ratio': 5,	'nombre': 'Caterpillar Inc.'},
    { 'ticker': 'CHL',	'ratio': 3,	'nombre': 'China Mobile Ltd.'},
    { 'ticker': 'CL',	'ratio': 3,	'nombre': 'Colgate-Palmolive Company'},
    { 'ticker': 'COST',	'ratio': 4,	'nombre': 'Costco Wholesale Corporation'},
    { 'ticker': 'CRM',	'ratio': 6,	'nombre': 'salesforce.com, inc.'},
    { 'ticker': 'CS',	'ratio': 1,	'nombre': 'Credit Suisse Group AG'},
    { 'ticker': 'CSCO',	'ratio': 5,	'nombre': 'Cisco Systems, Inc.'},
    { 'ticker': 'CVX',	'ratio': 8,	'nombre': 'Chevron Corporation'},
    { 'ticker': 'CX',	'ratio': 1,	'nombre': 'Cemex SAB de CV ADR'},
    { 'ticker': 'DD',	'ratio': 5,	'nombre': 'DuPont de Nemours Inc'},
    { 'ticker': 'DE',	'ratio': 2,	'nombre': 'Deere & Company'},
    { 'ticker': 'DESP',	'ratio': 1,	'nombre': 'Despegar.com Corp'},
    { 'ticker': 'DIS',	'ratio': 4,	'nombre': 'Walt Disney Co'},
    { 'ticker': 'EBAY',	'ratio': 1,	'nombre': 'eBay Inc'},
    { 'ticker': 'ERJ',	'ratio': 1,	'nombre': 'Embraer SA'},
    { 'ticker': 'FB',	'ratio': 8,	'nombre': 'Facebook, Inc. Common Stock'},
    { 'ticker': 'FCX',	'ratio': 1,	'nombre': 'Freeport-McMoRan Inc'},
    { 'ticker': 'FDX',	'ratio': 2,	'nombre': 'FedEx Corporation'},
    { 'ticker': 'FMX',	'ratio': 2,	'nombre': 'Fomento Economico Mexicano SAB ADR'},
    { 'ticker': 'GAZP',	'ratio': 2,	'nombre': 'PJSC GAZPROM '},
    { 'ticker': 'GE',	'ratio': 1,	'nombre': 'General Electric Company'},
    { 'ticker': 'GGB',	'ratio': 0.25,	'nombre': 'Gerdau SA ADR'},
    { 'ticker': 'GILD',	'ratio': 4,	'nombre': 'Gilead Sciences, Inc.'},
    { 'ticker': 'GLOB',	'ratio': 2,	'nombre': 'Globant SA'},
    { 'ticker': 'GOLD',	'ratio': 1,	'nombre': 'Barrick Gold Corp'},
    { 'ticker': 'GOOGL',	'ratio': 29,	'nombre': 'Alphabet Inc Class A'},
    { 'ticker': 'GRMN',	'ratio': 3,	'nombre': 'Garmin Ltd.'},
    { 'ticker': 'GS',	'ratio': 13,	'nombre': 'Goldman Sachs Group Inc'},
    { 'ticker': 'GSK',	'ratio': 4,	'nombre': 'GlaxoSmithKline plc'},
    { 'ticker': 'HD',	'ratio': 4,	'nombre': 'Home Depot Inc'},
    { 'ticker': 'HMC',	'ratio': 1,	'nombre': 'Honda Motor Co Ltd'},
    { 'ticker': 'HMY',	'ratio': 1,	'nombre': 'Harmony Gold Mining Co.'},
    { 'ticker': 'HNP',	'ratio': 1,	'nombre': 'Huaneng Power International Inc ADR Class N'},
    { 'ticker': 'HPQ',	'ratio': 1,	'nombre': 'HP Inc'},
    { 'ticker': 'HSBC',	'ratio': 2,	'nombre': 'HSBC Holdings plc'},
    { 'ticker': 'HWM',	'ratio': 1,	'nombre': 'Howmet Aerospace Inc'},
    { 'ticker': 'IBM',	'ratio': 5,	'nombre': 'IBM Common Stock'},
    { 'ticker': 'INFY',	'ratio': 1,	'nombre': 'Infosys Ltd ADR'},
    { 'ticker': 'INTC',	'ratio': 5,	'nombre': 'Intel Corporation'},
    { 'ticker': 'ITUB',	'ratio': 1,	'nombre': 'Itau Unibanco Holding SA ADR'},
    { 'ticker': 'JD',	'ratio': 2,	'nombre': 'JD.Com Inc'},
    { 'ticker': 'JNJ',	'ratio': 5,	'nombre': 'Johnson & Johnson'},
    { 'ticker': 'JPM',	'ratio': 5,	'nombre': 'JPMorgan Chase & Co.'},
    { 'ticker': 'KMB',	'ratio': 3,	'nombre': 'Kimberly Clark Corp'},
    { 'ticker': 'KO',	'ratio': 5,	'nombre': 'Coca-Cola Co'},
    { 'ticker': 'LMT',	'ratio': 1,	'nombre': 'Lockheed Martin Corporation'},
    { 'ticker': 'LVS',	'ratio': 1,	'nombre': 'Las Vegas Sands Corp.'},
    { 'ticker': 'LYG',	'ratio': 2,	'nombre': 'Lloyds Banking Group PLC'},
    { 'ticker': 'MCD',	'ratio': 4,	'nombre': 'Mcdonald\'s Corp'},
    { 'ticker': 'MDT',	'ratio': 2,	'nombre': 'Medtronic PLC'},
    { 'ticker': 'MELI',	'ratio': 2,	'nombre': 'Mercadolibre Inc'},
    { 'ticker': 'MMM',	'ratio': 5,	'nombre': '3M Co'},
    { 'ticker': 'MO',	'ratio': 4,	'nombre': 'Altria Group Inc'},
    { 'ticker': 'MRK',	'ratio': 5,	'nombre': 'Merck & Co., Inc.'},
    { 'ticker': 'MSFT',	'ratio': 5,	'nombre': 'Microsoft Corporation'},
    { 'ticker': 'MSI',	'ratio': 5,	'nombre': 'Motorola Solutions Inc'},
    { 'ticker': 'NEM',	'ratio': 1,	'nombre': 'Newmont Corporation'},
    { 'ticker': 'NFLX',	'ratio': 16,	'nombre': 'Netflix Inc'},
    { 'ticker': 'NGG',	'ratio': 2,	'nombre': 'National Grid plc'},
    { 'ticker': 'NKE',	'ratio': 3,	'nombre': 'Nike Inc'},
    { 'ticker': 'NOK',	'ratio': 1,	'nombre': 'Nokia Oyj'},
    { 'ticker': 'NVDA',	'ratio': 12,	'nombre': 'NVIDIA Corporation'},
    { 'ticker': 'NVS',	'ratio': 2,	'nombre': 'Novartis AG'},
    { 'ticker': 'ORCL',	'ratio': 3,	'nombre': 'Oracle Corporation'},
    { 'ticker': 'PBR',	'ratio': 1,	'nombre': 'PETROLEO BRASIL/ADR'},
    { 'ticker': 'PEP',	'ratio': 2,	'nombre': 'PepsiCo, Inc.'},
    { 'ticker': 'PFE',	'ratio': 2,	'nombre': 'Pfizer Inc.'},
    { 'ticker': 'PG',	'ratio': 5,	'nombre': 'Procter & Gamble Co'},
    { 'ticker': 'PTR',	'ratio': 4,	'nombre': 'PetroChina Company Limited ADR'},
    { 'ticker': 'PYPL',	'ratio': 4,	'nombre': 'Paypal Holdings Inc'},
    { 'ticker': 'QCOM',	'ratio': 11,	'nombre': 'QUALCOMM, Inc.'},
    { 'ticker': 'RIO',	'ratio': 4,	'nombre': 'Rio Tinto plc ADR Common Stock'},
    { 'ticker': 'RTX',	'ratio': 5,	'nombre': 'Raytheon Technologies Corp'},
    { 'ticker': 'SAN',	'ratio': 0.25,	'nombre': 'Banco Santander SA'},
    { 'ticker': 'SAP',	'ratio': 3,	'nombre': 'SAP SE'},
    { 'ticker': 'SBS',	'ratio': 0.5,	'nombre': 'Companhia de Saneamento Bsc DEDSP'},
    { 'ticker': 'SBUX',	'ratio': 1,	'nombre': 'Starbucks Corporation'},
    { 'ticker': 'SID',	'ratio': 0.125,	'nombre': 'Companhia Siderurgica Nacional'},
    { 'ticker': 'SLB',	'ratio': 3,	'nombre': 'Schlumberger NV'},
    { 'ticker': 'SNAP',	'ratio': 1,	'nombre': 'Snap Inc'},
    { 'ticker': 'SNE',	'ratio': 2,	'nombre': 'Sony Corp'},
    { 'ticker': 'SNP',	'ratio': 3,	'nombre': 'China Petroleum & Chemical Corp ADR'},
    { 'ticker': 'T',	'ratio': 3,	'nombre': 'AT&T Inc.'},
    { 'ticker': 'TGT',	'ratio': 4,	'nombre': 'Target Corporation'},
    { 'ticker': 'TM',	'ratio': 5,	'nombre': 'Toyota Motor Corp'},
    { 'ticker': 'TOT',	'ratio': 3,	'nombre': 'Total SA'},
    { 'ticker': 'TRIP',	'ratio': 2,	'nombre': 'Tripadvisor Inc Common Stock'},
    { 'ticker': 'TSLA',	'ratio': 15,	'nombre': 'Tesla Inc'},
    { 'ticker': 'TSM',	'ratio': 0.33,	'nombre': 'Taiwan Semiconductor Mfg. Co. Ltd.'},
    { 'ticker': 'TSU',	'ratio': 1,	'nombre': 'TIM Participacoes SA'},
    { 'ticker': 'TWTR',	'ratio': 1,	'nombre': 'Twitter Inc'},
    { 'ticker': 'TXN',	'ratio': 5,	'nombre': 'Texas Instruments Incorporated'},
    { 'ticker': 'UGP',	'ratio': 1,	'nombre': 'Ultrapar Participacoes SA'},
    { 'ticker': 'UN',	'ratio': 3,	'nombre': 'Unilever NV'},
    { 'ticker': 'V',	'ratio': 6,	'nombre': 'Visa Inc'},
    { 'ticker': 'VALE',	'ratio': 2,	'nombre': 'Vale SA'},
    { 'ticker': 'VIST',	'ratio': 0.2,	'nombre': 'VISTA OIL & GAS/S ADR'},
    { 'ticker': 'VIV',	'ratio': 1,	'nombre': 'Telefonica Brasil SA ADR'},
    { 'ticker': 'VOD',	'ratio': 1,	'nombre': 'Vodafone Group Plc'},
    { 'ticker': 'VRSN',	'ratio': 6,	'nombre': 'Verisign, Inc.'},
    { 'ticker': 'VZ',	'ratio': 2,	'nombre': 'Verizon Communications Inc.'},
    { 'ticker': 'WFC',	'ratio': 5,	'nombre': 'Wells Fargo & Co'},
    { 'ticker': 'WMT',	'ratio': 3,	'nombre': 'Walmart Inc'},
    { 'ticker': 'X',	'ratio': 3,	'nombre': 'United States Steel Corporation'},
    { 'ticker': 'XOM',	'ratio': 5,	'nombre': 'Exxon Mobil Corporation'},
    { 'ticker': 'YELP',	'ratio': 2,	'nombre': 'Yelp Inc'}
]
